### ISSUE TITLE
Gatt keyboard server support

### ISSUE THREAD

**Issue by HeadHodge** [ukBaz/BLE_GATT#5]
Hi,

I'm using my PI4-b to create a GATT HID (HOGP) Keyboard emulation server (peripheral), with python and the Bluez dbus api.

I have it working to the point that after connecting to my Windows 10, and Android phone, they will read my HIDInformation, ReportReference, and ReportMap characteristics. Then they invoke my StartNotify callback method in my Report characteristic.

That's where I'm stuck. I use the dbus 'changedproperties' signal to send reports to the client. But no matter what i do, i can't get the client to display a keypress on their display.

i cant tell if im sending the report incorrectly or providing an incorrect ReportMap characteristic value (i'm not wireshark competent yet with hci snoop dumps)..

Does your GATT client support the GATT HID service. if so, maybe it could be used to help troubleshoot my problem.  I'm also hoping you may have an actual keyboard example so i can see how to properly format my characteristic data.

Im also willing to donate some funds for any help your willing to provide, to help resolve my problem.

Thanks in Advance
Regards from sunny San Diego!

**Comment by ukBaz** [comment]
This library is not going to be able to help you much to create a client. You could use this library to connect to your HID keyboard, but at that point the OS takes over and creates an input device and read it as you would any other HID input. There are more details at: https://stackoverflow.com/a/54765300/7721752

I only have limited experience of creating a HID device and that was using the classic Bluetooth HID profile, not HoG. What I did is documented at:
https://gist.github.com/ukBaz/a47e71e7b87fbc851b27cde7d1c0fcf0

I am not sure this library can help much so I am going to close this issue.

Good luck with the project as it sounds interesting. If you get it working and post something publicly then please drop a link in this issue.

**Comment by HeadHodge** [comment]
Got lucky and got it working!!

Here is the example code: https://github.com/HeadHodge/Bluez-HID-over-GATT-Keyboard-Emulator-Example

I would be happy to see you add an update to your HID article to demonstrate a working Bluetooth 4.0 GATT alternative to your Classic Bluetooth 3.0 BR/EDR version.

Regards
From Sunny San Diego

**Comment by HeadHodge** [comment]
Thanks!

FYI, I discovered what a GIST was and created one of those for this example
https://gist.github.com/HeadHodge/2d3dc6dc2dce03cf82f61d8231e88144

Regards
From Sunny San Diego
